# Grafana Datasource Provisioning
#
# This file automatically configures Prometheus as a datasource in Grafana.
# Grafana will load this on startup, so you don't have to manually add datasources.
#
# Learning Objectives:
# - Understand Grafana datasource provisioning
# - Configure Prometheus datasource
# - Set up datasource for automatic dashboard creation
#
# References:
# - https://grafana.com/docs/grafana/latest/administration/provisioning/
# - https://grafana.com/docs/grafana/latest/datasources/prometheus/

apiVersion: 1

# TODO: Configure Prometheus datasource
# This tells Grafana where to fetch metrics from
#
# datasources:
#   - name: Prometheus
#     type: prometheus
#     access: proxy
#     url: http://prometheus:9090
#     isDefault: true
#     editable: true
#     jsonData:
#       timeInterval: "15s"
#       httpMethod: POST
#
# Parameters explained:
# - name: Display name in Grafana
# - type: Datasource type (prometheus, elasticsearch, etc.)
# - access: proxy = Grafana server fetches data (recommended)
#          direct = Browser fetches data (not recommended for security)
# - url: Prometheus server address
# - isDefault: Make this the default datasource for new dashboards
# - editable: Allow users to modify datasource settings in UI
# - timeInterval: Default scrape interval (should match Prometheus config)
# - httpMethod: POST for complex queries, GET for simple

# TODO: Add Elasticsearch datasource (optional, for logs)
# Useful if you want to visualize logs in Grafana alongside metrics
#
#   - name: Elasticsearch
#     type: elasticsearch
#     access: proxy
#     url: http://elasticsearch:9200
#     database: "logs-*"
#     jsonData:
#       esVersion: "8.11.0"
#       timeField: "@timestamp"
#       logMessageField: "message"
#       logLevelField: "level"
#       interval: "Daily"
#       timeInterval: "10s"
#
# Parameters explained:
# - database: Index pattern to query (logs-* = logs-2025.10.18, logs-2025.10.17, etc.)
# - timeField: Field containing timestamp
# - logMessageField: Field containing log message
# - logLevelField: Field containing log level (INFO, ERROR, etc.)
# - interval: How indices are rotated (Daily, Monthly, etc.)
